import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import "aos/dist/aos.css";
import AOSInit from "@/components/AOSInit";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/context/ModalContext";
import WhatsAppFloat from "@/components/WhatsappFloat";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SLP Marketing Agency",
  description: "Generated by create next app",
   icons: {
    icon: "/logo.png"
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable,"dark") } 
    >
      <body className="min-h-full flex flex-col">
        <ModalProvider>
        <AOSInit/>
        {children}
        <WhatsAppFloat/>

        </ModalProvider></body>
    </html>
  );
}
